apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
       - name: udagram-api-feed
         image: nuel07/udagram-api-feed:v3e
         imagePullPolicy: Always
         resources:
           requests:
             memory: "800Mi"
             cpu: "250m"
           limits:
             memory: "1700Mi"
             cpu: "500m"
         envFrom:
           - secretRef:
               name: env-secret
           - configMapRef:
               name: env-config
           - secretRef:
               name: nuelaws
         ports:
         - containerPort: 8080
