apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuel-feed
  labels:
    app: nuel-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuel-feed
  template:
    metadata:
      labels:
        app: nuel-feed
    spec:
      containers:
       - name: udagram-api-feed
         image: nuel07/udagram-api-feed:v3d
         imagePullPolicy: Always
         resources:
           requests:
             memory: "128Mi"
             cpu: "250m"
           limits:
             memory: "1024Mi"
             cpu: "500m"
         envFrom:
           - secretRef:
               name: env-secret
           - configMapRef:
               name: env-configmap
           - secretRef:
               name: aws-secret
         ports:
         - containerPort: 8080
